
FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package.json package-lock.json turbo.json tsconfig.json ./


COPY apps ./apps
COPY packages ./packages



# Install dependencies
RUN npm install
RUN npm run db:generate

# Build the application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm","run","start-user-app"]